version: "3"
services: 
  catalogo:
    container_name: catalogo
    build: ./api-catalogo
    command: npm start
    ports: 
      - 3000:3000
    working_dir: /usr/app
    volumes: 
      - ./api-catalogo:/usr/app
    depends_on: 
      - mongo

  recomendacoes:
    container_name: recomendacoes
    build: ./api-recomendacoes
    command: npm start
    ports: 
      - 4000:4000
    working_dir: /usr/app
    volumes: 
      - ./api-recomendacoes:/usr/app
    depends_on: 
      - catalogo
  mongo:
    container_name: mongo
    image: mongo
    ports: 
      - 27017:27017
  mongo_seed:
    build: ./mongo_seed
    depends_on: 
      - mongo